scss:
  enabled: true
  config_file: .scss-lint.yml
ruby:
  enabled: true
  config_file: .rubocop.yml
javascript:
  enabled: false
eslint:
  enabled: false
  config_file: .eslintrc
  ignore_file: .eslintignore
