language: node_js
node_js:
  - "6.9.2"
dist: trusty
before_install:
  - git submodule update --init --recursive
  - git fetch origin master:refs/remotes/origin/master --depth=1
addons:
  chrome: stable
install:
  - npm install
notifications:
  email:
    on_success: never
    on_failure: change
