language: node_js
node_js:
  - 6

before_install:
  - git submodule update --init --recursive

install:
  - yarn

before_script:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 0.18.1
  - npm install -g grunt-cli

script:
  - grunt test

notifications:
  email:
    on_success: never
    on_failure: change

cache: yarn