language: node_js
node_js:
  - "6.9.2"

before_install:
  - git submodule update --init --recursive

install:
  - npm install --no-optional

before_script:
  - npm install -g npm@3.10.9
  - npm install -g grunt-cli

script:
  - grunt test

notifications:
  email:
    on_success: never
    on_failure: change
