language: node_js
node_js:
  - "6.9.2"
dist: trusty
before_install:
  - git submodule update --init --recursive
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 0.18.1

  - git fetch origin master:refs/remotes/origin/master --depth=1
addons:
  chrome: stable
install:
  - yarn

before_script:
  - npm install -g npm@3.10.9
  - npm install -g grunt-cli

script:
  - grunt test

notifications:
  email:
    on_success: never
    on_failure: change

cache: yarn
