---
javascripts:
- base:
  - jquery.min.js
- dashboard:
  - admin/dashboard.js
- public_tables:
  - admin/public_tables.js
- table:
  - plugins/jquery.livequery.min.js
  - plugins/tag-it.js
  - plugins/cDBtable.js
  - admin/table_elements.js
  - admin/table.js

stylesheets:
- base:
  - reset
- home:
  - front/home
- sessions:
  - front/sessions
- dashboard:
  - admin/dashboard
- public_tables:
  - admin/public_tables
- table:
  - admin/table
  - admin/cDBtable
