name: Rubocop
on:
  push:
    branches-ignore:
      - master

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Rubocop checks
        uses: andrewmcodes/rubocop-linter-action@v3.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
