name: Rubocop
on:
  push:
    branches-ignore:
      - master

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Run rubocop with reviewdog
        uses: reviewdog/action-rubocop@v1
        with:
          # GITHUB_TOKEN.
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # rubocop flags. (rubocop <rubocop_flags>)
          # rubocop_flags: # optional, default is 
          # Tool name to use for reviewdog reporter
          # tool_name: # optional, default is rubocop
          # Report level for reviewdog [info,warning,error]
          level: info
          # Reporter of reviewdog command [github-pr-check,github-pr-review]
          reporter: github-pr-check
