name: Rubocop
on:
  push:
    branches-ignore:
      - master

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Rubocop checks
        uses: lyttco/github-actions-rubocop@1.3.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
